### ISSUE TITLE
Meta issue for governance

### ISSUE THREAD

**Issue by luceos** [flarum/governance#1]
Hi there 👋 ,

This repository is meant as a public library for our more official organisational documentation. We are hoping to fill this with articles that clarify our goals for Flarum, our team and ecosystem.

This issue acts as a todo for the bare minimum we wish to include as topics in this repository.

- [ ] Strategy
  - [ ] Flarum project strategy
- [ ] Organization
  - [ ] Divisions explained (Tech, Community, Flarum languages and Foundation)
  - [ ] Our processes (Cycles, meetings, releasing)
  - [ ] Task groups (themeing, search, i18n/utf8/asian market, extension ecosystem)
- [ ] Style/design guide

> This issue is still under review, more items will be added.

**Comment by luceos** [comment]
For clarification, my idea for task groups are people from different divisions to work on one goal. This goal has to be specific. Task groups potentially can dissolve once the goal has been completed.
